version: '3'
services:
  backend:
    build: ./api
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production

  frontend:
    build: ./client
    container_name: frontend
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend