version: '3'
services:
  backend:
    build: ./api
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb+srv://ak007:ak007@cluster0.6knv2.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      # If your application expects a different variable name, use that, e.g.:
      # - DATABASE_URL=your_mongodb_connection_string

  frontend:
    build: ./client
    container_name: frontend
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend